vdl_commons_profile:
  target: transformer
  outputs:
    transformer:
      type: "snowflake"
      account: "wx23413.europe-west4.gcp"
      user: "{{ env_var('DBT_USR') }}"
      password: "{{ env_var('DBT_PWD') }}"
      role: commons_tranformer
      database: "{{ env_var('COMMONS_DB') }}"
      warehouse: "commons_transformer"
      schema: "public"
      threads: 1
      client_session_keep_alive: False
    loader:
      type: "snowflake"
      account: "wx23413.europe-west4.gcp"
      user: "{{ env_var('DBT_USR') }}"
      password: "{{ env_var('DBT_PWD') }}"
      role: "commons_loader"
      database: "{{ env_var('COMMONS_DB') }}"
      warehouse: "commons_loader"
      schema: "raw"
      threads: 1
      client_session_keep_alive: False
    constructor:
      type: "snowflake"
      account: "wx23413.europe-west4.gcp"
      user: "{{ env_var('DBT_USR') }}"
      password: "{{ env_var('DBT_PWD') }}"
      role: "sysadmin"
      database: "commons"
      warehouse: "commons_loader"
      schema: "public"
      threads: 1
      client_session_keep_alive: False
    sso:
      type: snowflake
      account: "wx23413.europe-west4.gcp"
      user: "{{ env_var('DBT_USR') }}"
      role: "regnskap_transformer"
      # SSO config
      authenticator: externalbrowser
      database: "{{ env_var('REGNSKAP_DB') }}"
      warehouse: "regnskap_transformer"
      schema: "PUBLIC"
      threads: 1
      client_session_keep_alive: False
      reuse_connections: True
config:
  send_anonymous_usage_stats: False
