id: commons

databases:
  - name: commons
    transient: false
    data_retention_time_in_days: 1
    schemas:
      - name: raw
        transient: false
        data_retention_time_in_days: 90
      - name: stages
      - name: intermediates
      - name: marts
      - name: policies

roles:
  - name: commons_loader
  - name: commons_transformer
  - name: commons_reporter

warehouses:
  - name: commons_loader
  - name: commons_transformer
  - name: commons_reporter

grants:
  - role: commons_loader
    warehouses:
      - commons_loader
    write_on_schemas:
      - commons.raw
  - role: commons_transformer
    warehouses:
      - commons_transformer
    read_on_schemas:
      - commons.raw
    write_on_schemas:
      - commons.stages
      - commons.intermediates
      - commons.marts
      - commons.policies
  - role: commons_reporter
    warehouses:
      - commons_reporter
    read_on_schemas:
      - commons.marts
    to_roles:
      - eiendom_transformer
      - regnskap_transformer
      - innkjop_transformer
      - reporting_transformer
      - faktura_transformer
